// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void spk_packet_tx (
hls::stream<struct mua_struct >& mua_stream,
hls::stream<struct spk_struct >& out_pre,
hls::stream<struct spk_struct >& out_post,
hls::stream<int >& time_stamp,
ap_uint<32>* busy);
