// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->
    typedef struct mua_struct {
        int user;
        ap_uint<5> id;
        ap_uint<96> data;
       } mua_struct;

          typedef struct spk_struct {
              ap_uint<5> user;
              ap_uint<5> id;
              bool last;
              ap_uint<96> data;
             } spk_struct;



// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "mua_stream_V_user"
#define AUTOTB_TVIN_mua_stream_V_user  "../tv/cdatafile/c.spk_packet_tx.autotvin_mua_stream_V_user.dat"
#define WRAPC_STREAM_SIZE_IN_mua_stream_V_user  "../tv/stream_size/stream_size_in_mua_stream_V_user.dat"
#define WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user  "../tv/stream_size/stream_ingress_status_mua_stream_V_user.dat"
// wrapc file define: "mua_stream_V_id_V"
#define AUTOTB_TVIN_mua_stream_V_id_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_mua_stream_V_id_V.dat"
#define WRAPC_STREAM_SIZE_IN_mua_stream_V_id_V  "../tv/stream_size/stream_size_in_mua_stream_V_id_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V  "../tv/stream_size/stream_ingress_status_mua_stream_V_id_V.dat"
// wrapc file define: "mua_stream_V_data_V"
#define AUTOTB_TVIN_mua_stream_V_data_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_mua_stream_V_data_V.dat"
#define WRAPC_STREAM_SIZE_IN_mua_stream_V_data_V  "../tv/stream_size/stream_size_in_mua_stream_V_data_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V  "../tv/stream_size/stream_ingress_status_mua_stream_V_data_V.dat"
// wrapc file define: "out_pre_V_user_V"
#define AUTOTB_TVOUT_out_pre_V_user_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_pre_V_user_V.dat"
#define AUTOTB_TVIN_out_pre_V_user_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_pre_V_user_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V  "../tv/stream_size/stream_size_out_out_pre_V_user_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_pre_V_user_V  "../tv/stream_size/stream_egress_status_out_pre_V_user_V.dat"
// wrapc file define: "out_pre_V_id_V"
#define AUTOTB_TVOUT_out_pre_V_id_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_pre_V_id_V.dat"
#define AUTOTB_TVIN_out_pre_V_id_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_pre_V_id_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_pre_V_id_V  "../tv/stream_size/stream_size_out_out_pre_V_id_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_pre_V_id_V  "../tv/stream_size/stream_egress_status_out_pre_V_id_V.dat"
// wrapc file define: "out_pre_V_last"
#define AUTOTB_TVOUT_out_pre_V_last  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_pre_V_last.dat"
#define AUTOTB_TVIN_out_pre_V_last  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_pre_V_last.dat"
#define WRAPC_STREAM_SIZE_OUT_out_pre_V_last  "../tv/stream_size/stream_size_out_out_pre_V_last.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_pre_V_last  "../tv/stream_size/stream_egress_status_out_pre_V_last.dat"
// wrapc file define: "out_pre_V_data_V"
#define AUTOTB_TVOUT_out_pre_V_data_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_pre_V_data_V.dat"
#define AUTOTB_TVIN_out_pre_V_data_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_pre_V_data_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_pre_V_data_V  "../tv/stream_size/stream_size_out_out_pre_V_data_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_pre_V_data_V  "../tv/stream_size/stream_egress_status_out_pre_V_data_V.dat"
// wrapc file define: "out_post_V_user_V"
#define AUTOTB_TVOUT_out_post_V_user_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_post_V_user_V.dat"
#define AUTOTB_TVIN_out_post_V_user_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_post_V_user_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_post_V_user_V  "../tv/stream_size/stream_size_out_out_post_V_user_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_post_V_user_V  "../tv/stream_size/stream_egress_status_out_post_V_user_V.dat"
// wrapc file define: "out_post_V_id_V"
#define AUTOTB_TVOUT_out_post_V_id_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_post_V_id_V.dat"
#define AUTOTB_TVIN_out_post_V_id_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_post_V_id_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_post_V_id_V  "../tv/stream_size/stream_size_out_out_post_V_id_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_post_V_id_V  "../tv/stream_size/stream_egress_status_out_post_V_id_V.dat"
// wrapc file define: "out_post_V_last"
#define AUTOTB_TVOUT_out_post_V_last  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_post_V_last.dat"
#define AUTOTB_TVIN_out_post_V_last  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_post_V_last.dat"
#define WRAPC_STREAM_SIZE_OUT_out_post_V_last  "../tv/stream_size/stream_size_out_out_post_V_last.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_post_V_last  "../tv/stream_size/stream_egress_status_out_post_V_last.dat"
// wrapc file define: "out_post_V_data_V"
#define AUTOTB_TVOUT_out_post_V_data_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_out_post_V_data_V.dat"
#define AUTOTB_TVIN_out_post_V_data_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_out_post_V_data_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_post_V_data_V  "../tv/stream_size/stream_size_out_out_post_V_data_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_post_V_data_V  "../tv/stream_size/stream_egress_status_out_post_V_data_V.dat"
// wrapc file define: "time_stamp_V"
#define AUTOTB_TVOUT_time_stamp_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_time_stamp_V.dat"
#define AUTOTB_TVIN_time_stamp_V  "../tv/cdatafile/c.spk_packet_tx.autotvin_time_stamp_V.dat"
#define WRAPC_STREAM_SIZE_OUT_time_stamp_V  "../tv/stream_size/stream_size_out_time_stamp_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_time_stamp_V  "../tv/stream_size/stream_egress_status_time_stamp_V.dat"
// wrapc file define: "busy_V"
#define AUTOTB_TVOUT_busy_V  "../tv/cdatafile/c.spk_packet_tx.autotvout_busy_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "out_pre_V_user_V"
#define AUTOTB_TVOUT_PC_out_pre_V_user_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_pre_V_user_V.dat"
// tvout file define: "out_pre_V_id_V"
#define AUTOTB_TVOUT_PC_out_pre_V_id_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_pre_V_id_V.dat"
// tvout file define: "out_pre_V_last"
#define AUTOTB_TVOUT_PC_out_pre_V_last  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_pre_V_last.dat"
// tvout file define: "out_pre_V_data_V"
#define AUTOTB_TVOUT_PC_out_pre_V_data_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_pre_V_data_V.dat"
// tvout file define: "out_post_V_user_V"
#define AUTOTB_TVOUT_PC_out_post_V_user_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_post_V_user_V.dat"
// tvout file define: "out_post_V_id_V"
#define AUTOTB_TVOUT_PC_out_post_V_id_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_post_V_id_V.dat"
// tvout file define: "out_post_V_last"
#define AUTOTB_TVOUT_PC_out_post_V_last  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_post_V_last.dat"
// tvout file define: "out_post_V_data_V"
#define AUTOTB_TVOUT_PC_out_post_V_data_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_out_post_V_data_V.dat"
// tvout file define: "time_stamp_V"
#define AUTOTB_TVOUT_PC_time_stamp_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_time_stamp_V.dat"
// tvout file define: "busy_V"
#define AUTOTB_TVOUT_PC_busy_V  "../tv/rtldatafile/rtl.spk_packet_tx.autotvout_busy_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			mua_stream_V_user_depth = 0;
			mua_stream_V_id_V_depth = 0;
			mua_stream_V_data_V_depth = 0;
			out_pre_V_user_V_depth = 0;
			out_pre_V_id_V_depth = 0;
			out_pre_V_last_depth = 0;
			out_pre_V_data_V_depth = 0;
			out_post_V_user_V_depth = 0;
			out_post_V_id_V_depth = 0;
			out_post_V_last_depth = 0;
			out_post_V_data_V_depth = 0;
			time_stamp_V_depth = 0;
			busy_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{mua_stream_V_user " << mua_stream_V_user_depth << "}\n";
			total_list << "{mua_stream_V_id_V " << mua_stream_V_id_V_depth << "}\n";
			total_list << "{mua_stream_V_data_V " << mua_stream_V_data_V_depth << "}\n";
			total_list << "{out_pre_V_user_V " << out_pre_V_user_V_depth << "}\n";
			total_list << "{out_pre_V_id_V " << out_pre_V_id_V_depth << "}\n";
			total_list << "{out_pre_V_last " << out_pre_V_last_depth << "}\n";
			total_list << "{out_pre_V_data_V " << out_pre_V_data_V_depth << "}\n";
			total_list << "{out_post_V_user_V " << out_post_V_user_V_depth << "}\n";
			total_list << "{out_post_V_id_V " << out_post_V_id_V_depth << "}\n";
			total_list << "{out_post_V_last " << out_post_V_last_depth << "}\n";
			total_list << "{out_post_V_data_V " << out_post_V_data_V_depth << "}\n";
			total_list << "{time_stamp_V " << time_stamp_V_depth << "}\n";
			total_list << "{busy_V " << busy_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int mua_stream_V_user_depth;
		int mua_stream_V_id_V_depth;
		int mua_stream_V_data_V_depth;
		int out_pre_V_user_V_depth;
		int out_pre_V_id_V_depth;
		int out_pre_V_last_depth;
		int out_pre_V_data_V_depth;
		int out_post_V_user_V_depth;
		int out_post_V_id_V_depth;
		int out_post_V_last_depth;
		int out_post_V_data_V_depth;
		int time_stamp_V_depth;
		int busy_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define spk_packet_tx AESL_ORIG_DUT_spk_packet_tx
extern void spk_packet_tx (
hls::stream<mua_struct >& mua_stream,
hls::stream<spk_struct >& out_pre,
hls::stream<spk_struct >& out_post,
hls::stream<int >& time_stamp,
ap_uint<32>* busy);
#undef spk_packet_tx

void spk_packet_tx (
hls::stream<mua_struct >& mua_stream,
hls::stream<spk_struct >& out_pre,
hls::stream<spk_struct >& out_post,
hls::stream<int >& time_stamp,
ap_uint<32>* busy)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "mua_stream"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				mua_stream.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "out_pre"
		std::vector<spk_struct > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "out_pre"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "out_post"
		std::vector<spk_struct > aesl_tmp_6;
		int aesl_tmp_7;
		int aesl_tmp_8 = 0;

		// read output stream size: "out_post"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, AESL_token); // pop_size
			aesl_tmp_7 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "time_stamp"
		std::vector<int > aesl_tmp_9;
		int aesl_tmp_10;
		int aesl_tmp_11 = 0;

		// read output stream size: "time_stamp"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_time_stamp_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_time_stamp_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_time_stamp_V, AESL_token); // pop_size
			aesl_tmp_10 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_time_stamp_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "out_pre_V_user_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_user_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_user_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_user_V, AESL_token); // data

			std::vector<sc_bv<5> > out_pre_V_user_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_user_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_user_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_pre_V_user_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_user_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_pre_V_user_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					spk_struct tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_pre_V_user_V
				{
					// bitslice(4, 0)
					// {
						// celement: out_pre.V.user.V(4, 0)
						// {
							sc_lv<5>* out_pre_V_user_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<5>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.user.V(4, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].user) != NULL) // check the null address if the c port is array or others
									{
										out_pre_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(4, 0) = sc_bv<5>(out_pre_V_user_V_pc_buffer[hls_map_index].range(4, 0));
									}
								}
							}
						}
					}

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.user.V(4, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].user
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].user
									// output_left_conversion : aesl_tmp_3[i_0].user
									// output_type_conversion : (out_pre_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_3[0].user) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].user = (out_pre_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_pre_V_id_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_id_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_id_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_id_V, AESL_token); // data

			std::vector<sc_bv<5> > out_pre_V_id_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_id_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_id_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_pre_V_id_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_id_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_pre_V_id_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					spk_struct tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_pre_V_id_V
				{
					// bitslice(4, 0)
					// {
						// celement: out_pre.V.id.V(4, 0)
						// {
							sc_lv<5>* out_pre_V_id_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<5>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.id.V(4, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].id) != NULL) // check the null address if the c port is array or others
									{
										out_pre_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(4, 0) = sc_bv<5>(out_pre_V_id_V_pc_buffer[hls_map_index].range(4, 0));
									}
								}
							}
						}
					}

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.id.V(4, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].id
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].id
									// output_left_conversion : aesl_tmp_3[i_0].id
									// output_type_conversion : (out_pre_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_3[0].id) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].id = (out_pre_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_pre_V_last"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_last, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_last, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_last, AESL_token); // data

			std::vector<sc_bv<1> > out_pre_V_last_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_pre_V_last_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_last, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_pre_V_last))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					spk_struct tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_pre_V_last
				{
					// bitslice(0, 0)
					// {
						// celement: out_pre.V.last(0, 0)
						// {
							sc_lv<1>* out_pre_V_last_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.last(0, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
									{
										out_pre_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(0, 0) = sc_bv<1>(out_pre_V_last_pc_buffer[hls_map_index].range(0, 0));
									}
								}
							}
						}
					}

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.last(0, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].last
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].last
									// output_left_conversion : aesl_tmp_3[i_0].last
									// output_type_conversion : (out_pre_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_uint64()
									if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].last = (out_pre_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_uint64();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_pre_V_data_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_data_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_data_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_data_V, AESL_token); // data

			std::vector<sc_bv<96> > out_pre_V_data_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pre_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_pre_V_data_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_pre_V_data_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_pre_V_data_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					spk_struct tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_pre_V_data_V
				{
					// bitslice(95, 0)
					// {
						// celement: out_pre.V.data.V(95, 0)
						// {
							sc_lv<96>* out_pre_V_data_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<96>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(95, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.data.V(95, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
									{
										out_pre_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(95, 0) = sc_bv<96>(out_pre_V_data_V_pc_buffer[hls_map_index].range(95, 0));
									}
								}
							}
						}
					}

					// bitslice(95, 0)
					{
						int hls_map_index = 0;
						// celement: out_pre.V.data.V(95, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].data
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].data
									// output_left_conversion : aesl_tmp_3[i_0].data
									// output_type_conversion : (out_pre_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].data = (out_pre_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_post_V_user_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_user_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_user_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_user_V, AESL_token); // data

			std::vector<sc_bv<5> > out_post_V_user_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_user_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_user_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_post_V_user_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_user_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_post_V_user_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_7)
			{
				aesl_tmp_7 = i;
			}

			if (aesl_tmp_7 > 0 && aesl_tmp_6.size() < aesl_tmp_7)
			{
				int aesl_tmp_6_size = aesl_tmp_6.size();

				for (int tmp_aesl_tmp_6 = 0; tmp_aesl_tmp_6 < aesl_tmp_7 - aesl_tmp_6_size; tmp_aesl_tmp_6++)
				{
					spk_struct tmp;
					aesl_tmp_6.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_post_V_user_V
				{
					// bitslice(4, 0)
					// {
						// celement: out_post.V.user.V(4, 0)
						// {
							sc_lv<5>* out_post_V_user_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<5>[aesl_tmp_7 - aesl_tmp_8];
						// }
					// }

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.user.V(4, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_6[0].user) != NULL) // check the null address if the c port is array or others
									{
										out_post_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(4, 0) = sc_bv<5>(out_post_V_user_V_pc_buffer[hls_map_index].range(4, 0));
									}
								}
							}
						}
					}

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.user.V(4, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_6[i_0].user
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_6[0].user
									// output_left_conversion : aesl_tmp_6[i_0].user
									// output_type_conversion : (out_post_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_6[0].user) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_6[i_0].user = (out_post_V_user_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_post_V_id_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_id_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_id_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_id_V, AESL_token); // data

			std::vector<sc_bv<5> > out_post_V_id_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_id_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_id_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_post_V_id_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_id_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_post_V_id_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_7)
			{
				aesl_tmp_7 = i;
			}

			if (aesl_tmp_7 > 0 && aesl_tmp_6.size() < aesl_tmp_7)
			{
				int aesl_tmp_6_size = aesl_tmp_6.size();

				for (int tmp_aesl_tmp_6 = 0; tmp_aesl_tmp_6 < aesl_tmp_7 - aesl_tmp_6_size; tmp_aesl_tmp_6++)
				{
					spk_struct tmp;
					aesl_tmp_6.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_post_V_id_V
				{
					// bitslice(4, 0)
					// {
						// celement: out_post.V.id.V(4, 0)
						// {
							sc_lv<5>* out_post_V_id_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<5>[aesl_tmp_7 - aesl_tmp_8];
						// }
					// }

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.id.V(4, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_6[0].id) != NULL) // check the null address if the c port is array or others
									{
										out_post_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(4, 0) = sc_bv<5>(out_post_V_id_V_pc_buffer[hls_map_index].range(4, 0));
									}
								}
							}
						}
					}

					// bitslice(4, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.id.V(4, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_6[i_0].id
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_6[0].id
									// output_left_conversion : aesl_tmp_6[i_0].id
									// output_type_conversion : (out_post_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_6[0].id) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_6[i_0].id = (out_post_V_id_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_post_V_last"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_last, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_last, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_last, AESL_token); // data

			std::vector<sc_bv<1> > out_post_V_last_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_post_V_last_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_last, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_post_V_last))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_7)
			{
				aesl_tmp_7 = i;
			}

			if (aesl_tmp_7 > 0 && aesl_tmp_6.size() < aesl_tmp_7)
			{
				int aesl_tmp_6_size = aesl_tmp_6.size();

				for (int tmp_aesl_tmp_6 = 0; tmp_aesl_tmp_6 < aesl_tmp_7 - aesl_tmp_6_size; tmp_aesl_tmp_6++)
				{
					spk_struct tmp;
					aesl_tmp_6.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_post_V_last
				{
					// bitslice(0, 0)
					// {
						// celement: out_post.V.last(0, 0)
						// {
							sc_lv<1>* out_post_V_last_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_7 - aesl_tmp_8];
						// }
					// }

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.last(0, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_6[0].last) != NULL) // check the null address if the c port is array or others
									{
										out_post_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(0, 0) = sc_bv<1>(out_post_V_last_pc_buffer[hls_map_index].range(0, 0));
									}
								}
							}
						}
					}

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.last(0, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_6[i_0].last
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_6[0].last
									// output_left_conversion : aesl_tmp_6[i_0].last
									// output_type_conversion : (out_post_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_uint64()
									if (&(aesl_tmp_6[0].last) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_6[i_0].last = (out_post_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_uint64();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_post_V_data_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_data_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_data_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_data_V, AESL_token); // data

			std::vector<sc_bv<96> > out_post_V_data_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_post_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_post_V_data_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_post_V_data_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_post_V_data_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_7)
			{
				aesl_tmp_7 = i;
			}

			if (aesl_tmp_7 > 0 && aesl_tmp_6.size() < aesl_tmp_7)
			{
				int aesl_tmp_6_size = aesl_tmp_6.size();

				for (int tmp_aesl_tmp_6 = 0; tmp_aesl_tmp_6 < aesl_tmp_7 - aesl_tmp_6_size; tmp_aesl_tmp_6++)
				{
					spk_struct tmp;
					aesl_tmp_6.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_post_V_data_V
				{
					// bitslice(95, 0)
					// {
						// celement: out_post.V.data.V(95, 0)
						// {
							sc_lv<96>* out_post_V_data_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<96>[aesl_tmp_7 - aesl_tmp_8];
						// }
					// }

					// bitslice(95, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.data.V(95, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_6[0].data) != NULL) // check the null address if the c port is array or others
									{
										out_post_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++].range(95, 0) = sc_bv<96>(out_post_V_data_V_pc_buffer[hls_map_index].range(95, 0));
									}
								}
							}
						}
					}

					// bitslice(95, 0)
					{
						int hls_map_index = 0;
						// celement: out_post.V.data.V(95, 0)
						{
							// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
							for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_6[i_0].data
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_6[0].data
									// output_left_conversion : aesl_tmp_6[i_0].data
									// output_type_conversion : (out_post_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_6[0].data) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_6[i_0].data = (out_post_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "time_stamp_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_time_stamp_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_time_stamp_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_time_stamp_V, AESL_token); // data

			std::vector<sc_bv<32> > time_stamp_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'time_stamp_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'time_stamp_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					time_stamp_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_time_stamp_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_time_stamp_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_10)
			{
				aesl_tmp_10 = i;
			}

			if (aesl_tmp_10 > 0 && aesl_tmp_9.size() < aesl_tmp_10)
			{
				int aesl_tmp_9_size = aesl_tmp_9.size();

				for (int tmp_aesl_tmp_9 = 0; tmp_aesl_tmp_9 < aesl_tmp_10 - aesl_tmp_9_size; tmp_aesl_tmp_9++)
				{
					int tmp;
					aesl_tmp_9.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: time_stamp_V
				{
					// bitslice(31, 0)
					// {
						// celement: time_stamp.V(31, 0)
						// {
							sc_lv<32>* time_stamp_V_lv0_0_0_1 = new sc_lv<32>[aesl_tmp_10 - aesl_tmp_11];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: time_stamp.V(31, 0)
						{
							// carray: (aesl_tmp_11) => (aesl_tmp_10 - 1) @ (1)
							for (int i_0 = aesl_tmp_11; i_0 <= aesl_tmp_10 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
								{
									time_stamp_V_lv0_0_0_1[hls_map_index++].range(31, 0) = sc_bv<32>(time_stamp_V_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: time_stamp.V(31, 0)
						{
							// carray: (aesl_tmp_11) => (aesl_tmp_10 - 1) @ (1)
							for (int i_0 = aesl_tmp_11; i_0 <= aesl_tmp_10 - 1; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : aesl_tmp_9[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : aesl_tmp_9[0]
								// output_left_conversion : aesl_tmp_9[i_0]
								// output_type_conversion : (time_stamp_V_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_9[i_0] = (time_stamp_V_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "busy_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_busy_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_busy_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_busy_V, AESL_token); // data

			sc_bv<32> *busy_V_pc_buffer = new sc_bv<32>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'busy_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'busy_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					busy_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_busy_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_busy_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: busy_V
				{
					// bitslice(31, 0)
					// {
						// celement: busy.V(31, 0)
						// {
							sc_lv<32>* busy_V_lv0_0_0_1 = new sc_lv<32>[1];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: busy.V(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(busy[0]) != NULL) // check the null address if the c port is array or others
								{
									busy_V_lv0_0_0_1[hls_map_index++].range(31, 0) = sc_bv<32>(busy_V_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: busy.V(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : busy[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : busy[0]
								// output_left_conversion : busy[i_0]
								// output_type_conversion : (busy_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
								if (&(busy[0]) != NULL) // check the null address if the c port is array or others
								{
									busy[i_0] = (busy_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] busy_V_pc_buffer;
		}

		// push back output stream: "out_pre"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pre.write(aesl_tmp_3[i]);
		}

		// push back output stream: "out_post"
		for (int i = 0; i < aesl_tmp_7; i++)
		{
			out_post.write(aesl_tmp_6[i]);
		}

		// push back output stream: "time_stamp"
		for (int i = 0; i < aesl_tmp_10; i++)
		{
			time_stamp.write(aesl_tmp_9[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "mua_stream_V_user"
		char* tvin_mua_stream_V_user = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_mua_stream_V_user);
		char* wrapc_stream_size_in_mua_stream_V_user = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_mua_stream_V_user);
		char* wrapc_stream_ingress_status_mua_stream_V_user = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user);

		// "mua_stream_V_id_V"
		char* tvin_mua_stream_V_id_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_mua_stream_V_id_V);
		char* wrapc_stream_size_in_mua_stream_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_mua_stream_V_id_V);
		char* wrapc_stream_ingress_status_mua_stream_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V);

		// "mua_stream_V_data_V"
		char* tvin_mua_stream_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_mua_stream_V_data_V);
		char* wrapc_stream_size_in_mua_stream_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_mua_stream_V_data_V);
		char* wrapc_stream_ingress_status_mua_stream_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V);

		// "out_pre_V_user_V"
		char* tvin_out_pre_V_user_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_pre_V_user_V);
		char* tvout_out_pre_V_user_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_pre_V_user_V);
		char* wrapc_stream_size_out_out_pre_V_user_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V);
		char* wrapc_stream_egress_status_out_pre_V_user_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_pre_V_user_V);

		// "out_pre_V_id_V"
		char* tvin_out_pre_V_id_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_pre_V_id_V);
		char* tvout_out_pre_V_id_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_pre_V_id_V);
		char* wrapc_stream_size_out_out_pre_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_pre_V_id_V);
		char* wrapc_stream_egress_status_out_pre_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_pre_V_id_V);

		// "out_pre_V_last"
		char* tvin_out_pre_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_pre_V_last);
		char* tvout_out_pre_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_pre_V_last);
		char* wrapc_stream_size_out_out_pre_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_pre_V_last);
		char* wrapc_stream_egress_status_out_pre_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_pre_V_last);

		// "out_pre_V_data_V"
		char* tvin_out_pre_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_pre_V_data_V);
		char* tvout_out_pre_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_pre_V_data_V);
		char* wrapc_stream_size_out_out_pre_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_pre_V_data_V);
		char* wrapc_stream_egress_status_out_pre_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_pre_V_data_V);

		// "out_post_V_user_V"
		char* tvin_out_post_V_user_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_post_V_user_V);
		char* tvout_out_post_V_user_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_post_V_user_V);
		char* wrapc_stream_size_out_out_post_V_user_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V);
		char* wrapc_stream_egress_status_out_post_V_user_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_post_V_user_V);

		// "out_post_V_id_V"
		char* tvin_out_post_V_id_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_post_V_id_V);
		char* tvout_out_post_V_id_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_post_V_id_V);
		char* wrapc_stream_size_out_out_post_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_post_V_id_V);
		char* wrapc_stream_egress_status_out_post_V_id_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_post_V_id_V);

		// "out_post_V_last"
		char* tvin_out_post_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_post_V_last);
		char* tvout_out_post_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_post_V_last);
		char* wrapc_stream_size_out_out_post_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_post_V_last);
		char* wrapc_stream_egress_status_out_post_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_post_V_last);

		// "out_post_V_data_V"
		char* tvin_out_post_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_post_V_data_V);
		char* tvout_out_post_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_post_V_data_V);
		char* wrapc_stream_size_out_out_post_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_post_V_data_V);
		char* wrapc_stream_egress_status_out_post_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_post_V_data_V);

		// "time_stamp_V"
		char* tvin_time_stamp_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_time_stamp_V);
		char* tvout_time_stamp_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_time_stamp_V);
		char* wrapc_stream_size_out_time_stamp_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_time_stamp_V);
		char* wrapc_stream_egress_status_time_stamp_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_time_stamp_V);

		// "busy_V"
		char* tvout_busy_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_busy_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "mua_stream"
		std::vector<mua_struct > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!mua_stream.empty())
		{
			aesl_tmp_0.push_back(mua_stream.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "out_pre"
		std::vector<spk_struct > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!out_pre.empty())
		{
			aesl_tmp_3.push_back(out_pre.read());
			aesl_tmp_4++;
		}

		// dump stream tvin: "out_post"
		std::vector<spk_struct > aesl_tmp_6;
		int aesl_tmp_7 = 0;
		while (!out_post.empty())
		{
			aesl_tmp_6.push_back(out_post.read());
			aesl_tmp_7++;
		}

		// dump stream tvin: "time_stamp"
		std::vector<int > aesl_tmp_9;
		int aesl_tmp_10 = 0;
		while (!time_stamp.empty())
		{
			aesl_tmp_9.push_back(time_stamp.read());
			aesl_tmp_10++;
		}

		// push back input stream: "mua_stream"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			mua_stream.write(aesl_tmp_0[i]);
		}

		// push back input stream: "out_pre"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pre.write(aesl_tmp_3[i]);
		}

		// push back input stream: "out_post"
		for (int i = 0; i < aesl_tmp_7; i++)
		{
			out_post.write(aesl_tmp_6[i]);
		}

		// push back input stream: "time_stamp"
		for (int i = 0; i < aesl_tmp_10; i++)
		{
			time_stamp.write(aesl_tmp_9[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_spk_packet_tx(mua_stream, out_pre, out_post, time_stamp, busy);

		CodeState = DUMP_OUTPUTS;
		// record input size to tv3: "mua_stream"
		int aesl_tmp_2 = mua_stream.size();

		// pop output stream: "out_pre"
		int aesl_tmp_5 = aesl_tmp_4;
		aesl_tmp_4 = 0;
     aesl_tmp_3.clear();
		while (!out_pre.empty())
		{
			aesl_tmp_3.push_back(out_pre.read());
			aesl_tmp_4++;
		}

		// pop output stream: "out_post"
		int aesl_tmp_8 = aesl_tmp_7;
		aesl_tmp_7 = 0;
     aesl_tmp_6.clear();
		while (!out_post.empty())
		{
			aesl_tmp_6.push_back(out_post.read());
			aesl_tmp_7++;
		}

		// pop output stream: "time_stamp"
		int aesl_tmp_11 = aesl_tmp_10;
		aesl_tmp_10 = 0;
     aesl_tmp_9.clear();
		while (!time_stamp.empty())
		{
			aesl_tmp_9.push_back(time_stamp.read());
			aesl_tmp_10++;
		}

		// [[transaction]]
		sprintf(tvin_mua_stream_V_user, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_user, tvin_mua_stream_V_user);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, tvin_mua_stream_V_user);

		sc_bv<32>* mua_stream_V_user_tvin_wrapc_buffer = new sc_bv<32>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: mua_stream_V_user
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: mua_stream.V.user(31, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_0[i_0].user
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_0[0].user
							// regulate_c_name       : mua_stream_V_user
							// input_type_conversion : aesl_tmp_0[i_0].user
							if (&(aesl_tmp_0[0].user) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> mua_stream_V_user_tmp_mem;
								mua_stream_V_user_tmp_mem = aesl_tmp_0[i_0].user;
								mua_stream_V_user_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = mua_stream_V_user_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_mua_stream_V_user, "%s\n", (mua_stream_V_user_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_mua_stream_V_user, tvin_mua_stream_V_user);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_mua_stream_V_user = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, stream_ingress_size_mua_stream_V_user.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_mua_stream_V_user--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, stream_ingress_size_mua_stream_V_user.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.mua_stream_V_user_depth);
		sprintf(tvin_mua_stream_V_user, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_user, tvin_mua_stream_V_user);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_user, tvin_mua_stream_V_user);

		// release memory allocation
		delete [] mua_stream_V_user_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_mua_stream_V_user, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, wrapc_stream_size_in_mua_stream_V_user);
		sprintf(wrapc_stream_size_in_mua_stream_V_user, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, wrapc_stream_size_in_mua_stream_V_user);
		sprintf(wrapc_stream_size_in_mua_stream_V_user, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_user, wrapc_stream_size_in_mua_stream_V_user);

		// [[transaction]]
		sprintf(tvin_mua_stream_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_id_V, tvin_mua_stream_V_id_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, tvin_mua_stream_V_id_V);

		sc_bv<5>* mua_stream_V_id_V_tvin_wrapc_buffer = new sc_bv<5>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: mua_stream_V_id_V
		{
			// bitslice(4, 0)
			{
				int hls_map_index = 0;
				// celement: mua_stream.V.id.V(4, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_0[i_0].id
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_0[0].id
							// regulate_c_name       : mua_stream_V_id_V
							// input_type_conversion : (aesl_tmp_0[i_0].id).to_string(2).c_str()
							if (&(aesl_tmp_0[0].id) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<5> mua_stream_V_id_V_tmp_mem;
								mua_stream_V_id_V_tmp_mem = (aesl_tmp_0[i_0].id).to_string(2).c_str();
								mua_stream_V_id_V_tvin_wrapc_buffer[hls_map_index++].range(4, 0) = mua_stream_V_id_V_tmp_mem.range(4, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_mua_stream_V_id_V, "%s\n", (mua_stream_V_id_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_mua_stream_V_id_V, tvin_mua_stream_V_id_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_mua_stream_V_id_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, stream_ingress_size_mua_stream_V_id_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_mua_stream_V_id_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, stream_ingress_size_mua_stream_V_id_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.mua_stream_V_id_V_depth);
		sprintf(tvin_mua_stream_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_id_V, tvin_mua_stream_V_id_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_id_V, tvin_mua_stream_V_id_V);

		// release memory allocation
		delete [] mua_stream_V_id_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_mua_stream_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_id_V, wrapc_stream_size_in_mua_stream_V_id_V);
		sprintf(wrapc_stream_size_in_mua_stream_V_id_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_id_V, wrapc_stream_size_in_mua_stream_V_id_V);
		sprintf(wrapc_stream_size_in_mua_stream_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_id_V, wrapc_stream_size_in_mua_stream_V_id_V);

		// [[transaction]]
		sprintf(tvin_mua_stream_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_data_V, tvin_mua_stream_V_data_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, tvin_mua_stream_V_data_V);

		sc_bv<96>* mua_stream_V_data_V_tvin_wrapc_buffer = new sc_bv<96>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: mua_stream_V_data_V
		{
			// bitslice(95, 0)
			{
				int hls_map_index = 0;
				// celement: mua_stream.V.data.V(95, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_0[i_0].data
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_0[0].data
							// regulate_c_name       : mua_stream_V_data_V
							// input_type_conversion : (aesl_tmp_0[i_0].data).to_string(2).c_str()
							if (&(aesl_tmp_0[0].data) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<96> mua_stream_V_data_V_tmp_mem;
								mua_stream_V_data_V_tmp_mem = (aesl_tmp_0[i_0].data).to_string(2).c_str();
								mua_stream_V_data_V_tvin_wrapc_buffer[hls_map_index++].range(95, 0) = mua_stream_V_data_V_tmp_mem.range(95, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_mua_stream_V_data_V, "%s\n", (mua_stream_V_data_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_mua_stream_V_data_V, tvin_mua_stream_V_data_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_mua_stream_V_data_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, stream_ingress_size_mua_stream_V_data_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_mua_stream_V_data_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, stream_ingress_size_mua_stream_V_data_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.mua_stream_V_data_V_depth);
		sprintf(tvin_mua_stream_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_mua_stream_V_data_V, tvin_mua_stream_V_data_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_mua_stream_V_data_V, tvin_mua_stream_V_data_V);

		// release memory allocation
		delete [] mua_stream_V_data_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_mua_stream_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_data_V, wrapc_stream_size_in_mua_stream_V_data_V);
		sprintf(wrapc_stream_size_in_mua_stream_V_data_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_data_V, wrapc_stream_size_in_mua_stream_V_data_V);
		sprintf(wrapc_stream_size_in_mua_stream_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_mua_stream_V_data_V, wrapc_stream_size_in_mua_stream_V_data_V);

		// [[transaction]]
		sprintf(tvout_out_pre_V_user_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_user_V, tvout_out_pre_V_user_V);

		sc_bv<5>* out_pre_V_user_V_tvout_wrapc_buffer = new sc_bv<5>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_pre_V_user_V
		{
			// bitslice(4, 0)
			{
				int hls_map_index = 0;
				// celement: out_pre.V.user.V(4, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].user
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].user
							// regulate_c_name       : out_pre_V_user_V
							// input_type_conversion : (aesl_tmp_3[i_0].user).to_string(2).c_str()
							if (&(aesl_tmp_3[0].user) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<5> out_pre_V_user_V_tmp_mem;
								out_pre_V_user_V_tmp_mem = (aesl_tmp_3[i_0].user).to_string(2).c_str();
								out_pre_V_user_V_tvout_wrapc_buffer[hls_map_index++].range(4, 0) = out_pre_V_user_V_tmp_mem.range(4, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_pre_V_user_V, "%s\n", (out_pre_V_user_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_pre_V_user_V, tvout_out_pre_V_user_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_pre_V_user_V_depth);
		sprintf(tvout_out_pre_V_user_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_user_V, tvout_out_pre_V_user_V);

		// release memory allocation
		delete [] out_pre_V_user_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_pre_V_user_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, wrapc_stream_size_out_out_pre_V_user_V);
		sprintf(wrapc_stream_size_out_out_pre_V_user_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, wrapc_stream_size_out_out_pre_V_user_V);
		sprintf(wrapc_stream_size_out_out_pre_V_user_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_user_V, wrapc_stream_size_out_out_pre_V_user_V);

		// [[transaction]]
		sprintf(tvout_out_pre_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_id_V, tvout_out_pre_V_id_V);

		sc_bv<5>* out_pre_V_id_V_tvout_wrapc_buffer = new sc_bv<5>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_pre_V_id_V
		{
			// bitslice(4, 0)
			{
				int hls_map_index = 0;
				// celement: out_pre.V.id.V(4, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].id
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].id
							// regulate_c_name       : out_pre_V_id_V
							// input_type_conversion : (aesl_tmp_3[i_0].id).to_string(2).c_str()
							if (&(aesl_tmp_3[0].id) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<5> out_pre_V_id_V_tmp_mem;
								out_pre_V_id_V_tmp_mem = (aesl_tmp_3[i_0].id).to_string(2).c_str();
								out_pre_V_id_V_tvout_wrapc_buffer[hls_map_index++].range(4, 0) = out_pre_V_id_V_tmp_mem.range(4, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_pre_V_id_V, "%s\n", (out_pre_V_id_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_pre_V_id_V, tvout_out_pre_V_id_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_pre_V_id_V_depth);
		sprintf(tvout_out_pre_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_id_V, tvout_out_pre_V_id_V);

		// release memory allocation
		delete [] out_pre_V_id_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_pre_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_id_V, wrapc_stream_size_out_out_pre_V_id_V);
		sprintf(wrapc_stream_size_out_out_pre_V_id_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_id_V, wrapc_stream_size_out_out_pre_V_id_V);
		sprintf(wrapc_stream_size_out_out_pre_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_id_V, wrapc_stream_size_out_out_pre_V_id_V);

		// [[transaction]]
		sprintf(tvout_out_pre_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_last, tvout_out_pre_V_last);

		sc_bv<1>* out_pre_V_last_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_pre_V_last
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: out_pre.V.last(0, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].last
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].last
							// regulate_c_name       : out_pre_V_last
							// input_type_conversion : aesl_tmp_3[i_0].last
							if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<1> out_pre_V_last_tmp_mem;
								out_pre_V_last_tmp_mem = aesl_tmp_3[i_0].last;
								out_pre_V_last_tvout_wrapc_buffer[hls_map_index++].range(0, 0) = out_pre_V_last_tmp_mem.range(0, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_pre_V_last, "%s\n", (out_pre_V_last_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_pre_V_last, tvout_out_pre_V_last);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_pre_V_last_depth);
		sprintf(tvout_out_pre_V_last, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_last, tvout_out_pre_V_last);

		// release memory allocation
		delete [] out_pre_V_last_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_pre_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_last, wrapc_stream_size_out_out_pre_V_last);
		sprintf(wrapc_stream_size_out_out_pre_V_last, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_last, wrapc_stream_size_out_out_pre_V_last);
		sprintf(wrapc_stream_size_out_out_pre_V_last, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_last, wrapc_stream_size_out_out_pre_V_last);

		// [[transaction]]
		sprintf(tvout_out_pre_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_data_V, tvout_out_pre_V_data_V);

		sc_bv<96>* out_pre_V_data_V_tvout_wrapc_buffer = new sc_bv<96>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_pre_V_data_V
		{
			// bitslice(95, 0)
			{
				int hls_map_index = 0;
				// celement: out_pre.V.data.V(95, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].data
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].data
							// regulate_c_name       : out_pre_V_data_V
							// input_type_conversion : (aesl_tmp_3[i_0].data).to_string(2).c_str()
							if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<96> out_pre_V_data_V_tmp_mem;
								out_pre_V_data_V_tmp_mem = (aesl_tmp_3[i_0].data).to_string(2).c_str();
								out_pre_V_data_V_tvout_wrapc_buffer[hls_map_index++].range(95, 0) = out_pre_V_data_V_tmp_mem.range(95, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_pre_V_data_V, "%s\n", (out_pre_V_data_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_pre_V_data_V, tvout_out_pre_V_data_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_pre_V_data_V_depth);
		sprintf(tvout_out_pre_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_pre_V_data_V, tvout_out_pre_V_data_V);

		// release memory allocation
		delete [] out_pre_V_data_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_pre_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_data_V, wrapc_stream_size_out_out_pre_V_data_V);
		sprintf(wrapc_stream_size_out_out_pre_V_data_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_data_V, wrapc_stream_size_out_out_pre_V_data_V);
		sprintf(wrapc_stream_size_out_out_pre_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pre_V_data_V, wrapc_stream_size_out_out_pre_V_data_V);

		// [[transaction]]
		sprintf(tvout_out_post_V_user_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_user_V, tvout_out_post_V_user_V);

		sc_bv<5>* out_post_V_user_V_tvout_wrapc_buffer = new sc_bv<5>[aesl_tmp_7 - aesl_tmp_8];

		// RTL Name: out_post_V_user_V
		{
			// bitslice(4, 0)
			{
				int hls_map_index = 0;
				// celement: out_post.V.user.V(4, 0)
				{
					// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
					for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_6[i_0].user
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_6[0].user
							// regulate_c_name       : out_post_V_user_V
							// input_type_conversion : (aesl_tmp_6[i_0].user).to_string(2).c_str()
							if (&(aesl_tmp_6[0].user) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<5> out_post_V_user_V_tmp_mem;
								out_post_V_user_V_tmp_mem = (aesl_tmp_6[i_0].user).to_string(2).c_str();
								out_post_V_user_V_tvout_wrapc_buffer[hls_map_index++].range(4, 0) = out_post_V_user_V_tmp_mem.range(4, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_7 - aesl_tmp_8; i++)
		{
			sprintf(tvout_out_post_V_user_V, "%s\n", (out_post_V_user_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_post_V_user_V, tvout_out_post_V_user_V);
		}

		tcl_file.set_num(aesl_tmp_7 - aesl_tmp_8, &tcl_file.out_post_V_user_V_depth);
		sprintf(tvout_out_post_V_user_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_user_V, tvout_out_post_V_user_V);

		// release memory allocation
		delete [] out_post_V_user_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_post_V_user_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, wrapc_stream_size_out_out_post_V_user_V);
		sprintf(wrapc_stream_size_out_out_post_V_user_V, "%d\n", aesl_tmp_7 - aesl_tmp_8);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, wrapc_stream_size_out_out_post_V_user_V);
		sprintf(wrapc_stream_size_out_out_post_V_user_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_user_V, wrapc_stream_size_out_out_post_V_user_V);

		// [[transaction]]
		sprintf(tvout_out_post_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_id_V, tvout_out_post_V_id_V);

		sc_bv<5>* out_post_V_id_V_tvout_wrapc_buffer = new sc_bv<5>[aesl_tmp_7 - aesl_tmp_8];

		// RTL Name: out_post_V_id_V
		{
			// bitslice(4, 0)
			{
				int hls_map_index = 0;
				// celement: out_post.V.id.V(4, 0)
				{
					// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
					for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_6[i_0].id
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_6[0].id
							// regulate_c_name       : out_post_V_id_V
							// input_type_conversion : (aesl_tmp_6[i_0].id).to_string(2).c_str()
							if (&(aesl_tmp_6[0].id) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<5> out_post_V_id_V_tmp_mem;
								out_post_V_id_V_tmp_mem = (aesl_tmp_6[i_0].id).to_string(2).c_str();
								out_post_V_id_V_tvout_wrapc_buffer[hls_map_index++].range(4, 0) = out_post_V_id_V_tmp_mem.range(4, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_7 - aesl_tmp_8; i++)
		{
			sprintf(tvout_out_post_V_id_V, "%s\n", (out_post_V_id_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_post_V_id_V, tvout_out_post_V_id_V);
		}

		tcl_file.set_num(aesl_tmp_7 - aesl_tmp_8, &tcl_file.out_post_V_id_V_depth);
		sprintf(tvout_out_post_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_id_V, tvout_out_post_V_id_V);

		// release memory allocation
		delete [] out_post_V_id_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_post_V_id_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_id_V, wrapc_stream_size_out_out_post_V_id_V);
		sprintf(wrapc_stream_size_out_out_post_V_id_V, "%d\n", aesl_tmp_7 - aesl_tmp_8);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_id_V, wrapc_stream_size_out_out_post_V_id_V);
		sprintf(wrapc_stream_size_out_out_post_V_id_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_id_V, wrapc_stream_size_out_out_post_V_id_V);

		// [[transaction]]
		sprintf(tvout_out_post_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_last, tvout_out_post_V_last);

		sc_bv<1>* out_post_V_last_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_7 - aesl_tmp_8];

		// RTL Name: out_post_V_last
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: out_post.V.last(0, 0)
				{
					// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
					for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_6[i_0].last
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_6[0].last
							// regulate_c_name       : out_post_V_last
							// input_type_conversion : aesl_tmp_6[i_0].last
							if (&(aesl_tmp_6[0].last) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<1> out_post_V_last_tmp_mem;
								out_post_V_last_tmp_mem = aesl_tmp_6[i_0].last;
								out_post_V_last_tvout_wrapc_buffer[hls_map_index++].range(0, 0) = out_post_V_last_tmp_mem.range(0, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_7 - aesl_tmp_8; i++)
		{
			sprintf(tvout_out_post_V_last, "%s\n", (out_post_V_last_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_post_V_last, tvout_out_post_V_last);
		}

		tcl_file.set_num(aesl_tmp_7 - aesl_tmp_8, &tcl_file.out_post_V_last_depth);
		sprintf(tvout_out_post_V_last, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_last, tvout_out_post_V_last);

		// release memory allocation
		delete [] out_post_V_last_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_post_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_last, wrapc_stream_size_out_out_post_V_last);
		sprintf(wrapc_stream_size_out_out_post_V_last, "%d\n", aesl_tmp_7 - aesl_tmp_8);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_last, wrapc_stream_size_out_out_post_V_last);
		sprintf(wrapc_stream_size_out_out_post_V_last, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_last, wrapc_stream_size_out_out_post_V_last);

		// [[transaction]]
		sprintf(tvout_out_post_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_data_V, tvout_out_post_V_data_V);

		sc_bv<96>* out_post_V_data_V_tvout_wrapc_buffer = new sc_bv<96>[aesl_tmp_7 - aesl_tmp_8];

		// RTL Name: out_post_V_data_V
		{
			// bitslice(95, 0)
			{
				int hls_map_index = 0;
				// celement: out_post.V.data.V(95, 0)
				{
					// carray: (aesl_tmp_8) => (aesl_tmp_7 - 1) @ (1)
					for (int i_0 = aesl_tmp_8; i_0 <= aesl_tmp_7 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_6[i_0].data
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_6[0].data
							// regulate_c_name       : out_post_V_data_V
							// input_type_conversion : (aesl_tmp_6[i_0].data).to_string(2).c_str()
							if (&(aesl_tmp_6[0].data) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<96> out_post_V_data_V_tmp_mem;
								out_post_V_data_V_tmp_mem = (aesl_tmp_6[i_0].data).to_string(2).c_str();
								out_post_V_data_V_tvout_wrapc_buffer[hls_map_index++].range(95, 0) = out_post_V_data_V_tmp_mem.range(95, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_7 - aesl_tmp_8; i++)
		{
			sprintf(tvout_out_post_V_data_V, "%s\n", (out_post_V_data_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_post_V_data_V, tvout_out_post_V_data_V);
		}

		tcl_file.set_num(aesl_tmp_7 - aesl_tmp_8, &tcl_file.out_post_V_data_V_depth);
		sprintf(tvout_out_post_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_post_V_data_V, tvout_out_post_V_data_V);

		// release memory allocation
		delete [] out_post_V_data_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_post_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_data_V, wrapc_stream_size_out_out_post_V_data_V);
		sprintf(wrapc_stream_size_out_out_post_V_data_V, "%d\n", aesl_tmp_7 - aesl_tmp_8);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_data_V, wrapc_stream_size_out_out_post_V_data_V);
		sprintf(wrapc_stream_size_out_out_post_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_post_V_data_V, wrapc_stream_size_out_out_post_V_data_V);

		// [[transaction]]
		sprintf(tvout_time_stamp_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_time_stamp_V, tvout_time_stamp_V);

		sc_bv<32>* time_stamp_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_10 - aesl_tmp_11];

		// RTL Name: time_stamp_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: time_stamp.V(31, 0)
				{
					// carray: (aesl_tmp_11) => (aesl_tmp_10 - 1) @ (1)
					for (int i_0 = aesl_tmp_11; i_0 <= aesl_tmp_10 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_9[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_9[0]
						// regulate_c_name       : time_stamp_V
						// input_type_conversion : aesl_tmp_9[i_0]
						if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> time_stamp_V_tmp_mem;
							time_stamp_V_tmp_mem = aesl_tmp_9[i_0];
							time_stamp_V_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = time_stamp_V_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_10 - aesl_tmp_11; i++)
		{
			sprintf(tvout_time_stamp_V, "%s\n", (time_stamp_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_time_stamp_V, tvout_time_stamp_V);
		}

		tcl_file.set_num(aesl_tmp_10 - aesl_tmp_11, &tcl_file.time_stamp_V_depth);
		sprintf(tvout_time_stamp_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_time_stamp_V, tvout_time_stamp_V);

		// release memory allocation
		delete [] time_stamp_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_time_stamp_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_time_stamp_V, wrapc_stream_size_out_time_stamp_V);
		sprintf(wrapc_stream_size_out_time_stamp_V, "%d\n", aesl_tmp_10 - aesl_tmp_11);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_time_stamp_V, wrapc_stream_size_out_time_stamp_V);
		sprintf(wrapc_stream_size_out_time_stamp_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_time_stamp_V, wrapc_stream_size_out_time_stamp_V);

		// [[transaction]]
		sprintf(tvout_busy_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_busy_V, tvout_busy_V);

		sc_bv<32>* busy_V_tvout_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: busy_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: busy.V(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : busy[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : busy[0]
						// regulate_c_name       : busy_V
						// input_type_conversion : (busy[i_0]).to_string(2).c_str()
						if (&(busy[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> busy_V_tmp_mem;
							busy_V_tmp_mem = (busy[i_0]).to_string(2).c_str();
							busy_V_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = busy_V_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_busy_V, "%s\n", (busy_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_busy_V, tvout_busy_V);
		}

		tcl_file.set_num(1, &tcl_file.busy_V_depth);
		sprintf(tvout_busy_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_busy_V, tvout_busy_V);

		// release memory allocation
		delete [] busy_V_tvout_wrapc_buffer;

		// push back output stream: "out_pre"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pre.write(aesl_tmp_3[i]);
		}

		// push back output stream: "out_post"
		for (int i = 0; i < aesl_tmp_7; i++)
		{
			out_post.write(aesl_tmp_6[i]);
		}

		// push back output stream: "time_stamp"
		for (int i = 0; i < aesl_tmp_10; i++)
		{
			time_stamp.write(aesl_tmp_9[i]);
		}

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "mua_stream_V_user"
		delete [] tvin_mua_stream_V_user;
		delete [] wrapc_stream_size_in_mua_stream_V_user;
		// release memory allocation: "mua_stream_V_id_V"
		delete [] tvin_mua_stream_V_id_V;
		delete [] wrapc_stream_size_in_mua_stream_V_id_V;
		// release memory allocation: "mua_stream_V_data_V"
		delete [] tvin_mua_stream_V_data_V;
		delete [] wrapc_stream_size_in_mua_stream_V_data_V;
		// release memory allocation: "out_pre_V_user_V"
		delete [] tvout_out_pre_V_user_V;
		delete [] tvin_out_pre_V_user_V;
		delete [] wrapc_stream_size_out_out_pre_V_user_V;
		// release memory allocation: "out_pre_V_id_V"
		delete [] tvout_out_pre_V_id_V;
		delete [] tvin_out_pre_V_id_V;
		delete [] wrapc_stream_size_out_out_pre_V_id_V;
		// release memory allocation: "out_pre_V_last"
		delete [] tvout_out_pre_V_last;
		delete [] tvin_out_pre_V_last;
		delete [] wrapc_stream_size_out_out_pre_V_last;
		// release memory allocation: "out_pre_V_data_V"
		delete [] tvout_out_pre_V_data_V;
		delete [] tvin_out_pre_V_data_V;
		delete [] wrapc_stream_size_out_out_pre_V_data_V;
		// release memory allocation: "out_post_V_user_V"
		delete [] tvout_out_post_V_user_V;
		delete [] tvin_out_post_V_user_V;
		delete [] wrapc_stream_size_out_out_post_V_user_V;
		// release memory allocation: "out_post_V_id_V"
		delete [] tvout_out_post_V_id_V;
		delete [] tvin_out_post_V_id_V;
		delete [] wrapc_stream_size_out_out_post_V_id_V;
		// release memory allocation: "out_post_V_last"
		delete [] tvout_out_post_V_last;
		delete [] tvin_out_post_V_last;
		delete [] wrapc_stream_size_out_out_post_V_last;
		// release memory allocation: "out_post_V_data_V"
		delete [] tvout_out_post_V_data_V;
		delete [] tvin_out_post_V_data_V;
		delete [] wrapc_stream_size_out_out_post_V_data_V;
		// release memory allocation: "time_stamp_V"
		delete [] tvout_time_stamp_V;
		delete [] tvin_time_stamp_V;
		delete [] wrapc_stream_size_out_time_stamp_V;
		// release memory allocation: "busy_V"
		delete [] tvout_busy_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

