#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("pre_in_TUSER", 5, hls_in, 0, "axis", "in_data", 1),
	Port_Property("pre_in_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("pre_in_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("pre_in_TLAST", 1, hls_in, 1, "axis", "in_data", 1),
	Port_Property("pre_in_TID", 6, hls_in, 2, "axis", "in_data", 1),
	Port_Property("pre_in_TDATA", 96, hls_in, 3, "axis", "in_data", 1),
	Port_Property("post_in_TUSER", 5, hls_in, 4, "axis", "in_data", 1),
	Port_Property("post_in_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("post_in_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("post_in_TLAST", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("post_in_TID", 6, hls_in, 6, "axis", "in_data", 1),
	Port_Property("post_in_TDATA", 96, hls_in, 7, "axis", "in_data", 1),
	Port_Property("time_stamp_V_TDATA", 32, hls_in, 8, "axis", "in_data", 1),
	Port_Property("time_stamp_V_TVALID", 1, hls_in, 8, "axis", "in_vld", 1),
	Port_Property("time_stamp_V_TREADY", 1, hls_out, 8, "axis", "in_acc", 1),
	Port_Property("spk_out_stream_TID", 6, hls_out, 9, "axis", "out_data", 1),
	Port_Property("spk_out_stream_TVALID", 1, hls_out, 12, "axis", "out_vld", 1),
	Port_Property("spk_out_stream_TREADY", 1, hls_in, 12, "axis", "out_acc", 1),
	Port_Property("spk_out_stream_TUSER", 32, hls_out, 10, "axis", "out_data", 1),
	Port_Property("spk_out_stream_TDATA", 96, hls_out, 11, "axis", "out_data", 1),
	Port_Property("spk_out_stream_TDEST", 16, hls_out, 12, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "spk_packet_rx";
